In [1]:
import os
import sys
import pandas as pd

df_faostat_prices = pd.read_csv("data/FAOSTAT_prices.csv")

In [2]:
df_faostat_prices.head()

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Months Code,Months,Unit,Value,Flag,Flag Description
0,PP,Producer Prices,724,Spain,5532,Producer Price (USD/tonne),1330,Grapes,1991,1991,7021,Annual value,USD,528.4,A,Official figure
1,PP,Producer Prices,724,Spain,5532,Producer Price (USD/tonne),1330,Grapes,1992,1992,7021,Annual value,USD,532.6,A,Official figure
2,PP,Producer Prices,724,Spain,5532,Producer Price (USD/tonne),1330,Grapes,1993,1993,7021,Annual value,USD,411.1,A,Official figure
3,PP,Producer Prices,724,Spain,5532,Producer Price (USD/tonne),1330,Grapes,1994,1994,7021,Annual value,USD,564.8,A,Official figure
4,PP,Producer Prices,724,Spain,5532,Producer Price (USD/tonne),1330,Grapes,1995,1995,7021,Annual value,USD,735.4,A,Official figure

In [ ]:
df_faostat_prices = df_faostat_prices.loc[:,["Item Code (CPC)", "Item", "Year", "Unit", "Value"]]
grapes_prices = df_faostat_prices[df_faostat_prices["Item"] == "Grapes"].drop(columns=["Item Code (CPC)"])
maize_prices = df_faostat_prices[df_faostat_prices["Item"] == "Maize (corn)"].drop(columns=["Item Code (CPC)"])
sunflower_prices = df_faostat_prices[df_faostat_prices["Item"] == "Sunflower seed"].drop(columns=["Item Code (CPC)"])
tomatoes_prices = df_faostat_prices[df_faostat_prices["Item"] == "Tomatoes"].drop(columns=["Item Code (CPC)"])
wheat_prices = df_faostat_prices[df_faostat_prices["Item"] == "Wheat"].drop(columns=["Item Code (CPC)"])

In [ ]:
df_faostat_prices

     Item Code (CPC)    Item  Year Unit  Value
0               1330  Grapes  1991  USD  528.4
1               1330  Grapes  1992  USD  532.6
2               1330  Grapes  1993  USD  411.1
3               1330  Grapes  1994  USD  564.8
4               1330  Grapes  1995  USD  735.4
..               ...     ...   ...  ...    ...
165              111   Wheat  2020  USD  221.5
166              111   Wheat  2021  USD  299.1
167              111   Wheat  2022  USD  381.9
168              111   Wheat  2023  USD  299.0
169              111   Wheat  2024  USD  243.0

[170 rows x 5 columns]

In [5]:
df_faostat_prices["Item"].unique()

<StringArray>
['Grapes', 'Maize (corn)', 'Sunflower seed', 'Tomatoes', 'Wheat']
Length: 5, dtype: str

In [9]:
grapes_prices = df_faostat_prices[df_faostat_prices["Item"] == "Grapes"].drop(columns=["Item Code (CPC)"])
maize_prices = df_faostat_prices[df_faostat_prices["Item"] == "Maize (corn)"].drop(columns=["Item Code (CPC)"])
sunflower_prices = df_faostat_prices[df_faostat_prices["Item"] == "Sunflower seed"].drop(columns=["Item Code (CPC)"])
tomatoes_prices = df_faostat_prices[df_faostat_prices["Item"] == "Tomatoes"].drop(columns=["Item Code (CPC)"])
wheat_prices = df_faostat_prices[df_faostat_prices["Item"] == "Wheat"].drop(columns=["Item Code (CPC)"])

In [10]:
print(grapes_prices.head())
print(maize_prices.head())
print(sunflower_prices.head())
print(tomatoes_prices.head())
print(wheat_prices.head())

     Item  Year Unit  Value
0  Grapes  1991  USD  528.4
1  Grapes  1992  USD  532.6
2  Grapes  1993  USD  411.1
3  Grapes  1994  USD  564.8
4  Grapes  1995  USD  735.4
            Item  Year Unit  Value
34  Maize (corn)  1991  USD  263.9
35  Maize (corn)  1992  USD  250.4
36  Maize (corn)  1993  USD  223.8
37  Maize (corn)  1994  USD  198.5
38  Maize (corn)  1995  USD  222.2
              Item  Year Unit  Value
68  Sunflower seed  1991  USD  601.7
69  Sunflower seed  1992  USD  157.6
70  Sunflower seed  1993  USD  262.4
71  Sunflower seed  1994  USD  256.6
72  Sunflower seed  1995  USD  297.6
         Item  Year Unit  Value
102  Tomatoes  1991  USD  418.2
103  Tomatoes  1992  USD  372.5
104  Tomatoes  1993  USD  377.9
105  Tomatoes  1994  USD  364.2
106  Tomatoes  1995  USD  372.8
      Item  Year Unit  Value
136  Wheat  1991  USD  266.1
137  Wheat  1992  USD  261.3
138  Wheat  1993  USD  210.4
139  Wheat  1994  USD  200.3
140  Wheat  1995  USD  226.6

In [15]:
ipampa_overall_index = pd.read_csv("data/IPAMPA_overall_index.csv", sep=";")
ipampa_overall_index.rename(columns={"Label": "Year", "Annual agricultural means of production purchasing price index (IPAMPA) - Overall index": "IPAMPA_overall_index"}, inplace=True)
ipampa_overall_index.head()

   Year  IPAMPA_overall_index
0  2025                 124.7
1  2024                 125.4
2  2023                 131.2
3  2022                 133.7
4  2021                 109.2